<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNM8xVt3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNM8xVt3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNM8xVt3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNM8xVt3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNM8xVt3\App_KernelDevDebugContainer([
    'container.build_hash' => 'NM8xVt3',
    'container.build_id' => 'c5ec358b',
    'container.build_time' => 1641220937,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNM8xVt3');
